name: Run Playwright Tests with Allure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-playwright-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install

      # Step 4: Install Allure CLI
      - name: Install Allure CLI
        run: |
          sudo apt update
          sudo apt install -y openjdk-11-jdk
          curl -sLo allure.tgz https://github.com/allure-framework/allure2/releases/download/2.23.0/allure-2.23.0.tgz
          sudo tar -zxf allure.tgz -C /opt/
          sudo ln -sf /opt/allure-2.23.0/bin/allure /usr/bin/allure

      # Step 4.2: Set environment variables
      - name: Set environment variables
        run: echo "YT_STORAGE_STATE=${{ secrets.YT_STORAGE_STATE }}" >> $GITHUB_ENV
      
      # Step 5: Run Playwright tests
      - name: Run Playwright tests
        run: |
          pytest --alluredir=results/allure-results || true

      # Step 6: Generate Allure HTML Report
      - name: Generate Allure HTML Report
        run: |
          allure generate results/allure-results -o results/allure-report --clean
          ls -la results/allure-report  # Проверка созданных файлов

      # Step 7: Deploy Allure Report to GitHub Pages
      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: results/allure-report
