name: Run k6 Performance Tests with Setup and Execution

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-environment:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Install k6 and Node.js
      - name: Install k6 and Node.js
        run: |
          sudo apt update
          curl -s https://dl.k6.io/key.gpg | sudo apt-key add -
          echo "deb https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt update
          sudo apt install -y k6
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt install -y nodejs
          
      # Step 2: Cache environment
      - name: Cache environment
        uses: actions/cache@v3
        with:
          path: |
            /usr/bin/k6
            ~/.npm
            ~/.cache
          key: ${{ runner.os }}-k6-environment

      # Step 3: Verify installation
      - name: Verify k6 and Node.js installation
        run: |
          k6 version
          node -v
          npm -v

  run-tests:
    runs-on: ubuntu-latest
    needs: setup-environment
    steps:
      # Step 1: Restore cached environment
      - name: Restore environment from cache
        uses: actions/cache@v3
        with:
          path: |
            /usr/bin/k6
            ~/.npm
            ~/.cache
          key: ${{ runner.os }}-k6-environment

      # Step 2: Add /usr/bin to PATH
      - name: Add k6 to PATH
        run: echo "/usr/bin" >> $GITHUB_PATH

      # Step 3: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 4: Verify k6 is available
      - name: Verify k6 installation
        run: k6 version

      # Step 5: Run k6 tests
      - name: Run k6 tests
        run: |
          mkdir -p results
          k6 run ./tests/test_script.js --out json=results/output.json

      # Step 6: Upload test results
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: k6-results
          path: results/
