name: Run Performance Tests

on:
  workflow_run:
    workflows: ["Setup Environment"]
    types:
      - completed

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Download environment setup
      - name: Download environment setup
        uses: actions/download-artifact@v3
        with:
          name: environment-setup

      # Step 3: Run k6 tests
      - name: Run k6 tests
        run: |
          mkdir -p results
          k6 run ./tests/test_script.js --out json=results/output.json


      # Step 4: Upload test results
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: k6-results
          path: results/
